### ISSUE TITLE
This would be more useful as an actual CMake script that can be included in a project.

### ISSUE THREAD

**Issue by jherico** [mattjensjensen/latest_vkcpp#1]

**Comment by mattjensjensen** [comment]
I'd be happy to oblige but I primarily intended this to just provide an output folder of the headers that can be placed where you desire them. Do you have an idea for where you'd want the headers to go on all your development platforms? I work on GNU/Linux, Win10, and OSX so I have slightly different practices for using Vulkan on each.

**Comment by jherico** [comment]
I usually incorporate external projects into my own like so:

```
ExternalProject_Add(
    ${EXTERNAL_NAME}
    URL https://github.com/glfw/glfw/archive/3.2.zip
    URL_MD5 6028bc8cb169376ac1dad3ab3bd216cf
    CMAKE_ARGS ${PLATFORM_CMAKE_ARGS} -DCMAKE_INSTALL_PREFIX:PATH=<INSTALL_DIR>  -DGLFW_BUILD_EXAMPLES=OFF -DGLFW_BUILD_TESTS=OFF -DGLFW_BUILD_DOCS=OFF
    LOG_DOWNLOAD 1
)
```

So, assuming you make a CMakeLists.txt file that executes the git fetches and includes a set of install commands, I can use the CMAKE_INSTALL_PREFIX as above to cause the header to be generated and then put into a known location in my current project's build directory. 

I would also suggest making the Vulkan spec version targetable, either by allowing the user to specify a commit ID or by allowing the user to specify that the generation should use an already existing copy of the spec that's on the local system

**Comment by mattjensjensen** [comment]
I've expanded the script into a bit more powerful shell utility for fetching the development headers of specific commits from the Vulkan-Docs at Khronos. In the future I plan on allowing users to fetch by VK_HEADER_VERSION numbers or by VK_API_VERIONs. However, I want to make the final use for it agnostic to build systems, if you'd like to create a cmake script for using this I'd love to see it, but this project using cmake is only because vkcpp uses cmake to build its executable.
